[idris2]
url     = "https://github.com/idris-lang/Idris2.git"
version = "0.5.1"
commit  = "094a9ab06d68bea216d892058c5e323738cab858"

[db.apache-mime-types]
type   = "github"
url    = "https://github.com/kbertalan/idris2-apache-mime-types"
commit = "37ab5d1499ceb29fdbab64739da7a78559aaab5a"
ipkg   = "apache-mime-types.ipkg"

[db.bytestring]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-bytestring"
commit = "e06ca875ce5eba11bc3faa62f18ba652c0ea73a1"
ipkg   = "bytestring.ipkg"

[db.collie]
type   = "github"
url    = "https://github.com/ohad/collie"
commit = "46bff04a8d9a1598fec9b19f515541df16dc64ef"
ipkg   = "collie.ipkg"

[db.comonad]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-comonad"
commit = "35a6e7c2243e73e9c63340e532adaf3197cea3d3"
ipkg   = "comonad.ipkg"

[db.dinwiddy]
type   = "github"
url    = "https://github.com/bobbbay/dinwiddy"
commit = "61a81c55e48e4b7b551fb7493d623cb7659a37ce"
ipkg   = "dinwiddy.ipkg"

[db.dom]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-dom"
commit = "c4e0084b94ebc90d7b47fb4bf6e88aa31a3b1262"
ipkg   = "dom.ipkg"

[db.eff]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-eff"
commit = "5520bac8da3364bd3a02f4ac9bf318ce85479c6a"
ipkg   = "eff.ipkg"

[db.effect]
type   = "github"
url    = "https://github.com/Russoul/Idris2-Effect"
commit = "b76dce14b79a5f743243a294c3474c6f113f8e3a"
ipkg   = "effect.ipkg"

[db.elab-util]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "036b6d693dffe6efb508bfa2346705d51f9d0b61"
ipkg   = "elab-util.ipkg"

[db.freer]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-freer"
commit = "87f6104ed438f89e0176dbc7e9ea3f57128e683d"
ipkg   = "freer.ipkg"

[db.fvect]
type   = "github"
url    = "https://github.com/mattpolzin/idris-fvect"
commit = "d84969fce38ff8a10b9d261458f4d495e6e0f1ca"
ipkg   = "fvect.ipkg"

[db.graph]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-graph"
commit = "46ad8cb827e180dc781e87c095c7dba17b2b9756"
ipkg   = "graph.ipkg"

[db.hashable]
type   = "github"
url    = "https://github.com/Z-snails/Idris2-hashable"
commit = "d97d2c39d9199941e2de1991224f564fc4b956dd"
ipkg   = "hashable.ipkg"

[db.hashmap]
type   = "github"
url    = "https://github.com/Z-snails/idris2-hashmap"
commit = "dd2283a6e0fcfb71c0ad9076459ffdfb6110f18a"
ipkg   = "hashmap.ipkg"

[db.hedgehog]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-hedgehog"
commit = "c6074ae2ad34480c2179b3dd45bb4e4605961445"
ipkg   = "hedgehog.ipkg"

[db.idrall]
type   = "github"
url    = "https://github.com/alexhumphreys/idrall"
commit = "b5f04575c94cc5cc006791d81f106f5492e3b8f3"
ipkg   = "idrall.ipkg"

[db.indexed]
type   = "github"
url    = "https://github.com/mattpolzin/idris-indexed"
commit = "21e448e4da193425336ae150bc55e015c6445415"
ipkg   = "indexed.ipkg"

[db.json]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-json"
commit = "2b7b370ee0ffc5ed57437f2da548548dd0000e9d"
ipkg   = "json.ipkg"

[db.katla]
type   = "github"
url    = "https://github.com/idris-community/katla"
commit = "9213675856413c587094e588c2758390f0020faf"
ipkg   = "katla.ipkg"

[db.lsp]
type   = "github"
url    = "https://github.com/idris-community/idris2-lsp"
commit = "14a7786df970acc13a9d0b33e04fb9540d9cebb5"
ipkg   = "lsp.ipkg"

[db.pack]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-pack"
commit = "2c326998fc0d50d5e45f216328fc7f437301f7e1"
ipkg   = "pack.ipkg"

[db.pack-admin]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-pack-admin"
commit = "eeb1ba2939fc3a4c079e7cbdef6a368364fe9699"
ipkg   = "pack-admin.ipkg"

[db.pg-idris]
type   = "github"
url    = "https://github.com/mattpolzin/pg-idris"
commit = "6f7b2f6c96f963e5073c39613ccd394bc2f3ace5"
ipkg   = "pg-idris.ipkg"

[db.prettier]
type   = "github"
url    = "https://github.com/Z-snails/prettier"
commit = "0222ada0be5f6abf5528c8513181f2f4ad117b4b"
ipkg   = "prettier.ipkg"

[db.pretty-show]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-pretty-show"
commit = "09684725181ad4ba2ae8a49443bee358d7947c25"
ipkg   = "pretty-show.ipkg"

[db.prim]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-prim"
commit = "0ad39cd9b29336ce5cf5199af6754af1a085b0c6"
ipkg   = "prim.ipkg"

[db.rhone]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-rhone"
commit = "cc48d755e2a56a646063ed07a44d6a452dd0e488"
ipkg   = "rhone.ipkg"

[db.rhone-js]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-rhone-js"
commit = "4f37a9379b7e19609100db8ae062e0f3fd6a98f1"
ipkg   = "rhone-js.ipkg"

[db.snocvect]
type   = "github"
url    = "https://github.com/mattpolzin/idris-snocvect"
commit = "f6148c3d06c7a9989062a2425f925fc844468215"
ipkg   = "snocvect.ipkg"

[db.sop]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-sop"
commit = "1d8029c2bda9749d7c4ffe74d75b0bd7f51815d2"
ipkg   = "sop.ipkg"

[db.tailrec]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-tailrec"
commit = "ae27e2ed09ef3d880801899cfc26f470f5b71332"
ipkg   = "tailrec.ipkg"

[db.tester]
type   = "github"
url    = "https://github.com/cuddlefishie/tester-idr"
commit = "3dcdb54ed578a14597a17cb93c926734a9da69ca"
ipkg   = "tester.ipkg"

[db.toml]
type   = "github"
url    = "https://github.com/cuddlefishie/toml-idr"
commit = "b4f5a4bd874fa32f20d02311a62a1910dc48123f"
ipkg   = "toml.ipkg"

[db.tyttp]
type   = "github"
url    = "https://github.com/kbertalan/tyttp"
commit = "92113413b216a1866ffe2e8a99407a050f12f041"
ipkg   = "tyttp.ipkg"

[db.tyttp-json]
type   = "github"
url    = "https://github.com/kbertalan/tyttp-json"
commit = "956385e032243b04980b1f5dabf95411cce665ce"
ipkg   = "tyttp-json.ipkg"

[db.xml]
type   = "github"
url    = "https://github.com/madman-bob/idris2-xml"
commit = "1292ccfcd58c551089ef699e4560343d5c473d64"
ipkg   = "xml.ipkg"
